version: '3'

services:
  site:
    build: .
    volumes: 
      - ./:/var/www/html/
    depends_on:
      - db
    ports:
      - "8444:80"
  db:
    image: mysql:5.7.28
    container_name: dbmysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aviva
      MYSQL_USER: avivauser
      MYSQL_PASSWORD: avivapass
    volumes: 
        - ./aviva.sql:/docker-entrypoint-initdb.d/aviva.sql
    ports:
      - "8440:3306"
  myadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - "8441:80"
    links:
        - db:db